apiVersion: tekton.dev/v1beta1
kind: {{ .Values.task.kind }}
metadata:
  name: gotest-withtag
  namespace: {{ default "katanomi" .Values.task.namespace }}
spec:
  workspaces:
    - description: The git repo will be cloned onto the volume backing this workspace
      name: source
  params:
    - name: tools-image
      description: "image used to run commands"
      default: {{ .Values.task.image | quote }}
  steps:
    - name: check
      image: $(params.tools-image)
      env:
        - name: GOPRIVATE
          value: "github.com/katanomi/*"
      script: |
        #!/bin/bash
        set -eu

        cd $(workspaces.source.path)

        tags="$(grep -I  -r '// +build' . | \
          grep -v '^./vendor/' | \
          grep -v '^./hack/' | \
          grep -v '^./third_party' | \
          cut -f3 -d' ' | \
          sort | uniq | \
          grep -v '^!' | \
          tr '\n' ' ')"

        echo "Building with tags: ${tags}"
        go test -vet=off -tags "${tags}" ./...
